wesley/students/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views
from .filters import StudentFilter, ConsultFilter
from django_filters.views import FilterView


app_name = 'students'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('students/<int:pk>/', views.StudentDV.as_view(), name='student-detail'),
    path('consults/<int:pk>/', views.ConsultDV.as_view(), name='consult-detail'),
    path('students/<int:pk>/delete/',
         views.StudentDelete.as_view(), name='student-delete'),
    path('consults/<int:pk>/delete/',
         views.ConsultDelete.as_view(), name='consult-delete'),
    path('consults/<int:pk>/edit/', views.ConsultUV.as_view(), name='consult-edit'),
    path('students/<int:pk>/edit/', views.StudentUV.as_view(), name='student-edit'),
    path('students/create/', views.StudentCV.as_view(), name='student-new'),
    path('consults/create/', views.ConsultCV.as_view(), name='consult-new'),
    path('consults/search/', FilterView.as_view(filterset_class=ConsultFilter,
                                                template_name='students/consult_filter.html'), name='consult-search'),
    path('students/search/', FilterView.as_view(filterset_class=StudentFilter,
                                                template_name='students/student_filter.html'), name='student-search'),
    path('students/', views.StudentLV.as_view(), name='student-list'),
    path('consults/', views.ConsultLV.as_view(), name='consult-list'),
]

wesley/wesley/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students.urls')),
]

wesley/students/models.py
from django.urls import reverse
from django.db import models
from django.conf import settings
import datetime


STATUS_CHOICES = (
    ('대기', '대기'),
    ('재원', '재원'),
    ('휴원', '휴원'),
    ('퇴원', '퇴원'),
    ('예정', '예정'),
)

TYPE_CHOICES = (
    ('거절', '거절'),
    ('기존', '기존'),
    ('미배정', '미배정'),
    ('신규', '신규'),
    ('재입학', '재입학'),
)

TYPE_DETAIL_CHOICES = (
    ('우선 배정', '우선 배정'),
    ('다음 배정', '다음 배정'),
    ('내부 거절', '내부 거절'),
    ('외부 거절', '외부 거절'),
)

CLASS_CHOICES = (
    ('1A01', '1A01'),
    ('1A02', '1A02'),
    ('1A03', '1A03'),
    ('1A04', '1A04'),
    ('1A05', '1A05'),
    ('1A06', '1A06'),
    ('1A07', '1A07'),
    ('1A08', '1A08'),
    ('1A09', '1A09'),
    ('1A10', '1A10'),
    ('1A11', '1A11'),
    ('1A12', '1A12'),
    ('1B01', '1B01'),
    ('1B02', '1B02'),
    ('1B03', '1B03'),
    ('1B04', '1B04'),
    ('1B05', '1B05'),
    ('1B06', '1B06'),
    ('1B07', '1B07'),
    ('1B08', '1B08'),
    ('1B09', '1B09'),
    ('1B10', '1B10'),
    ('1B11', '1B11'),
    ('1B12', '1B12'),
    ('1C01', '1C01'),
    ('1C02', '1C02'),
    ('1C03', '1C03'),
    ('1C04', '1C04'),
    ('1C05', '1C05'),
    ('1C06', '1C06'),
    ('1C07', '1C07'),
    ('1C08', '1C08'),
    ('1C09', '1C09'),
    ('1C10', '1C10'),
    ('1C11', '1C11'),
    ('1C12', '1C12'),
    ('1D01', '1D01'),
    ('1D02', '1D02'),
    ('1D03', '1D03'),
    ('1D04', '1D04'),
    ('1D05', '1D05'),
    ('1D06', '1D06'),
    ('1D07', '1D07'),
    ('1D08', '1D08'),
    ('1D09', '1D09'),
    ('1D10', '1D10'),
    ('1D11', '1D11'),
    ('1D12', '1D12'),
    ('1E01', '1E01'),
    ('1E02', '1E02'),
    ('1E03', '1E03'),
    ('1E04', '1E04'),
    ('1E05', '1E05'),
    ('1E06', '1E06'),
    ('1E07', '1E07'),
    ('1E08', '1E08'),
    ('1E09', '1E09'),
    ('1E10', '1E10'),
    ('1E11', '1E11'),
    ('1E12', '1E12'),
    ('1F01', '1F01'),
    ('1F02', '1F02'),
    ('1F03', '1F03'),
    ('1F04', '1F04'),
    ('1F05', '1F05'),
    ('1F06', '1F06'),
    ('1F07', '1F07'),
    ('1F08', '1F08'),
    ('1F09', '1F09'),
    ('1F10', '1F10'),
    ('1F11', '1F11'),
    ('1F12', '1F12'),
    ('2A01', '2A01'),
    ('2A02', '2A02'),
    ('2A03', '2A03'),
    ('2A04', '2A04'),
    ('2A05', '2A05'),
    ('2A06', '2A06'),
    ('2A07', '2A07'),
    ('2A08', '2A08'),
    ('2A09', '2A09'),
    ('2A10', '2A10'),
    ('2A11', '2A11'),
    ('2A12', '2A12'),
    ('2B01', '2B01'),
    ('2B02', '2B02'),
    ('2B03', '2B03'),
    ('2B04', '2B04'),
    ('2B05', '2B05'),
    ('2B06', '2B06'),
    ('2B07', '2B07'),
    ('2B08', '2B08'),
    ('2B09', '2B09'),
    ('2B10', '2B10'),
    ('2B11', '2B11'),
    ('2B12', '2B12'),
    ('2C01', '2C01'),
    ('2C02', '2C02'),
    ('2C03', '2C03'),
    ('2C04', '2C04'),
    ('2C05', '2C05'),
    ('2C06', '2C06'),
    ('2C07', '2C07'),
    ('2C08', '2C08'),
    ('2C09', '2C09'),
    ('2C10', '2C10'),
    ('2C11', '2C11'),
    ('2C12', '2C12'),
    ('2D01', '2D01'),
    ('2D02', '2D02'),
    ('2D03', '2D03'),
    ('2D04', '2D04'),
    ('2D05', '2D05'),
    ('2D06', '2D06'),
    ('2D07', '2D07'),
    ('2D08', '2D08'),
    ('2D09', '2D09'),
    ('2D10', '2D10'),
    ('2D11', '2D11'),
    ('2D12', '2D12'),
    ('2E01', '2E01'),
    ('2E02', '2E02'),
    ('2E03', '2E03'),
    ('2E04', '2E04'),
    ('2E05', '2E05'),
    ('2E06', '2E06'),
    ('2E07', '2E07'),
    ('2E08', '2E08'),
    ('2E09', '2E09'),
    ('2E10', '2E10'),
    ('2E11', '2E11'),
    ('2E12', '2E12'),
    ('2F01', '2F01'),
    ('2F02', '2F02'),
    ('2F03', '2F03'),
    ('2F04', '2F04'),
    ('2F05', '2F05'),
    ('2F06', '2F06'),
    ('2F07', '2F07'),
    ('2F08', '2F08'),
    ('2F09', '2F09'),
    ('2F10', '2F10'),
    ('2F11', '2F11'),
    ('2F12', '2F12'),
    ('3A01', '3A01'),
    ('3A02', '3A02'),
    ('3A03', '3A03'),
    ('3A04', '3A04'),
    ('3A05', '3A05'),
    ('3A06', '3A06'),
    ('3A07', '3A07'),
    ('3A08', '3A08'),
    ('3A09', '3A09'),
    ('3A10', '3A10'),
    ('3A11', '3A11'),
    ('3A12', '3A12'),
    ('3B01', '3B01'),
    ('3B02', '3B02'),
    ('3B03', '3B03'),
    ('3B04', '3B04'),
    ('3B05', '3B05'),
    ('3B06', '3B06'),
    ('3B07', '3B07'),
    ('3B08', '3B08'),
    ('3B09', '3B09'),
    ('3B10', '3B10'),
    ('3B11', '3B11'),
    ('3B12', '3B12'),
    ('3C01', '3C01'),
    ('3C02', '3C02'),
    ('3C03', '3C03'),
    ('3C04', '3C04'),
    ('3C05', '3C05'),
    ('3C06', '3C06'),
    ('3C07', '3C07'),
    ('3C08', '3C08'),
    ('3C09', '3C09'),
    ('3C10', '3C10'),
    ('3C11', '3C11'),
    ('3C12', '3C12'),
    ('3D01', '3D01'),
    ('3D02', '3D02'),
    ('3D03', '3D03'),
    ('3D04', '3D04'),
    ('3D05', '3D05'),
    ('3D06', '3D06'),
    ('3D07', '3D07'),
    ('3D08', '3D08'),
    ('3D09', '3D09'),
    ('3D10', '3D10'),
    ('3D11', '3D11'),
    ('3D12', '3D12'),
    ('3E01', '3E01'),
    ('3E02', '3E02'),
    ('3E03', '3E03'),
    ('3E04', '3E04'),
    ('3E05', '3E05'),
    ('3E06', '3E06'),
    ('3E07', '3E07'),
    ('3E08', '3E08'),
    ('3E09', '3E09'),
    ('3E10', '3E10'),
    ('3E11', '3E11'),
    ('3E12', '3E12'),
    ('3F01', '3F01'),
    ('3F02', '3F02'),
    ('3F03', '3F03'),
    ('3F04', '3F04'),
    ('3F05', '3F05'),
    ('3F06', '3F06'),
    ('3F07', '3F07'),
    ('3F08', '3F08'),
    ('3F09', '3F09'),
    ('3F10', '3F10'),
    ('3F11', '3F11'),
    ('3F12', '3F12'),
    ('4A01', '4A01'),
    ('4A02', '4A02'),
    ('4A03', '4A03'),
    ('4A04', '4A04'),
    ('4A05', '4A05'),
    ('4A06', '4A06'),
    ('4A07', '4A07'),
    ('4A08', '4A08'),
    ('4A09', '4A09'),
    ('4A10', '4A10'),
    ('4A11', '4A11'),
    ('4A12', '4A12'),
    ('4B01', '4B01'),
    ('4B02', '4B02'),
    ('4B03', '4B03'),
    ('4B04', '4B04'),
    ('4B05', '4B05'),
    ('4B06', '4B06'),
    ('4B07', '4B07'),
    ('4B08', '4B08'),
    ('4B09', '4B09'),
    ('4B10', '4B10'),
    ('4B11', '4B11'),
    ('4B12', '4B12'),
    ('4C01', '4C01'),
    ('4C02', '4C02'),
    ('4C03', '4C03'),
    ('4C04', '4C04'),
    ('4C05', '4C05'),
    ('4C06', '4C06'),
    ('4C07', '4C07'),
    ('4C08', '4C08'),
    ('4C09', '4C09'),
    ('4C10', '4C10'),
    ('4C11', '4C11'),
    ('4C12', '4C12'),
    ('4D01', '4D01'),
    ('4D02', '4D02'),
    ('4D03', '4D03'),
    ('4D04', '4D04'),
    ('4D05', '4D05'),
    ('4D06', '4D06'),
    ('4D07', '4D07'),
    ('4D08', '4D08'),
    ('4D09', '4D09'),
    ('4D10', '4D10'),
    ('4D11', '4D11'),
    ('4D12', '4D12'),
    ('4E01', '4E01'),
    ('4E02', '4E02'),
    ('4E03', '4E03'),
    ('4E04', '4E04'),
    ('4E05', '4E05'),
    ('4E06', '4E06'),
    ('4E07', '4E07'),
    ('4E08', '4E08'),
    ('4E09', '4E09'),
    ('4E10', '4E10'),
    ('4E11', '4E11'),
    ('4E12', '4E12'),
    ('4F01', '4F01'),
    ('4F02', '4F02'),
    ('4F03', '4F03'),
    ('4F04', '4F04'),
    ('4F05', '4F05'),
    ('4F06', '4F06'),
    ('4F07', '4F07'),
    ('4F08', '4F08'),
    ('4F09', '4F09'),
    ('4F10', '4F10'),
    ('4F11', '4F11'),
    ('4F12', '4F12'),
    ('5A01', '5A01'),
    ('5A02', '5A02'),
    ('5A03', '5A03'),
    ('5A04', '5A04'),
    ('5A05', '5A05'),
    ('5A06', '5A06'),
    ('5A07', '5A07'),
    ('5A08', '5A08'),
    ('5A09', '5A09'),
    ('5A10', '5A10'),
    ('5A11', '5A11'),
    ('5A12', '5A12'),
    ('5B01', '5B01'),
    ('5B02', '5B02'),
    ('5B03', '5B03'),
    ('5B04', '5B04'),
    ('5B05', '5B05'),
    ('5B06', '5B06'),
    ('5B07', '5B07'),
    ('5B08', '5B08'),
    ('5B09', '5B09'),
    ('5B10', '5B10'),
    ('5B11', '5B11'),
    ('5B12', '5B12'),
    ('5C01', '5C01'),
    ('5C02', '5C02'),
    ('5C03', '5C03'),
    ('5C04', '5C04'),
    ('5C05', '5C05'),
    ('5C06', '5C06'),
    ('5C07', '5C07'),
    ('5C08', '5C08'),
    ('5C09', '5C09'),
    ('5C10', '5C10'),
    ('5C11', '5C11'),
    ('5C12', '5C12'),
    ('5D01', '5D01'),
    ('5D02', '5D02'),
    ('5D03', '5D03'),
    ('5D04', '5D04'),
    ('5D05', '5D05'),
    ('5D06', '5D06'),
    ('5D07', '5D07'),
    ('5D08', '5D08'),
    ('5D09', '5D09'),
    ('5D10', '5D10'),
    ('5D11', '5D11'),
    ('5D12', '5D12'),
    ('5E01', '5E01'),
    ('5E02', '5E02'),
    ('5E03', '5E03'),
    ('5E04', '5E04'),
    ('5E05', '5E05'),
    ('5E06', '5E06'),
    ('5E07', '5E07'),
    ('5E08', '5E08'),
    ('5E09', '5E09'),
    ('5E10', '5E10'),
    ('5E11', '5E11'),
    ('5E12', '5E12'),
    ('5F01', '5F01'),
    ('5F02', '5F02'),
    ('5F03', '5F03'),
    ('5F04', '5F04'),
    ('5F05', '5F05'),
    ('5F06', '5F06'),
    ('5F07', '5F07'),
    ('5F08', '5F08'),
    ('5F09', '5F09'),
    ('5F10', '5F10'),
    ('5F11', '5F11'),
    ('5F12', '5F12'),
    ('6A01', '6A01'),
    ('6A02', '6A02'),
    ('6A03', '6A03'),
    ('6A04', '6A04'),
    ('6A05', '6A05'),
    ('6A06', '6A06'),
    ('6A07', '6A07'),
    ('6A08', '6A08'),
    ('6A09', '6A09'),
    ('6A10', '6A10'),
    ('6A11', '6A11'),
    ('6A12', '6A12'),
    ('6B01', '6B01'),
    ('6B02', '6B02'),
    ('6B03', '6B03'),
    ('6B04', '6B04'),
    ('6B05', '6B05'),
    ('6B06', '6B06'),
    ('6B07', '6B07'),
    ('6B08', '6B08'),
    ('6B09', '6B09'),
    ('6B10', '6B10'),
    ('6B11', '6B11'),
    ('6B12', '6B12'),
    ('6C01', '6C01'),
    ('6C02', '6C02'),
    ('6C03', '6C03'),
    ('6C04', '6C04'),
    ('6C05', '6C05'),
    ('6C06', '6C06'),
    ('6C07', '6C07'),
    ('6C08', '6C08'),
    ('6C09', '6C09'),
    ('6C10', '6C10'),
    ('6C11', '6C11'),
    ('6C12', '6C12'),
    ('6D01', '6D01'),
    ('6D02', '6D02'),
    ('6D03', '6D03'),
    ('6D04', '6D04'),
    ('6D05', '6D05'),
    ('6D06', '6D06'),
    ('6D07', '6D07'),
    ('6D08', '6D08'),
    ('6D09', '6D09'),
    ('6D10', '6D10'),
    ('6D11', '6D11'),
    ('6D12', '6D12'),
    ('6E01', '6E01'),
    ('6E02', '6E02'),
    ('6E03', '6E03'),
    ('6E04', '6E04'),

wesley/students/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'


class ConsultForm(forms.ModelForm):
    class Meta:
        model = Consulting
        fields = '__all__'


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = '__all__'

wesley/students/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import *
from .forms import *
from .filters import StudentFilter
from django.contrib.auth.mixins import LoginRequiredMixin


def index(request):
    return render(request, 'students/index.html')


class ConsultCV(LoginRequiredMixin, CreateView):
    login_url = '/login'
    template_name = 'students/consult_new.html'
    form_class = ConsultForm

    def get_initial(self):
        return {
            "counselor": self.request.user
        }


class ConsultDV(DetailView):
    model = Consulting


class ConsultLV(LoginRequiredMixin, ListView):
    login_url = '/login'
    model = Consulting
    paginate_by = 20
    queryset = Consulting.objects.all()


class StudentLV(LoginRequiredMixin, ListView):
    login_url = '/login'
    model = Student
    paginate_by = 500

    def get_context_data(self, **kwargs):
        context = super(StudentLV, self).get_context_data(**kwargs)
        context['배정'] = Student.objects.filter(status='재원' or '휴원').count()
        context['미배정'] = Student.objects.filter(type_choices='미배정').count()
        context['총원'] = context['배정']+context['미배정']
        context['신규'] = Student.objects.filter(
            type_choices='신규').count()
        context['재입학'] = Student.objects.filter(
            type_choices='재입학').count()
        return context


class StudentCV(LoginRequiredMixin, CreateView):
    login_url = '/login'
    template_name = 'students/student_new.html'
    form_class = StudentForm


class ConsultUV(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Consulting
    context_object_name = 'consulting'
    form_class = ConsultForm
    template_name = 'students/consulting_edit.html'

    def get_object(self):
        consult = get_object_or_404(Consulting, pk=self.kwargs['pk'])
        return consult


class StudentUV(LoginRequiredMixin, UpdateView):
    login_url = '/login'
    model = Student
    context_object_name = 'student'
    form_class = StudentForm
    template_name = 'students/student_edit.html'

    def get_object(self):
        student = get_object_or_404(Student, pk=self.kwargs['pk'])
        return student


class StudentDV(LoginRequiredMixin, DetailView):
    login_url = '/login'
    model = Student

    def get_context_data(self, **kwargs):
        context = super(StudentDV, self).get_context_data(**kwargs)
        context['consult_list'] = Consulting.objects.filter(
            student=self.kwargs['pk'])
        return context


class StudentDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login'
    model = Student
    success_url = '/students'


class ConsultDelete(LoginRequiredMixin, DeleteView):
    login_url = '/login'
    model = Consulting
    success_url = '/consults'

wesley/students/templates/students/base.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Wesley</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:logout' %}">Log-out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:student-list' %}">전체 학생 조회</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:student-search' %}">학생 조건별 조회</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:consult-list' %}">전체 상담 조회</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'students:consult-search' %}">상담 조건별 조회</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Welcome,
                            {{ request.user.username}}</a>
                    </li>
                </ul>
                <form action="{% url 'students:student-search' %}" class="form-inline my-2 my-lg-0" method="get">
                    <input name="kor_name" class="form-control mr-sm-2" type="search" placeholder="학생명">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">검색하기</button>
                </form>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'students:login' %}">Log-in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">로그인이 필요합니다.</a>
                </li>
                </ul>
                {% endif %}

            </div>
        </nav>
        <div class="container-fluid">
            {% block content %}
            {% endblock %}
        </div>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
        </script>
    </body>

</html>

wesley/students/templates/students/student_detail.html
{% extends 'students/base.html' %}

{% block content %}
<div class='row'>

        <div class='col-sm'>
        </div>
    <div class='col-sm'>
        <div class="card">

            <table class="table table-bordered" style="text-align:center;">
                <thead class="thead-light">
                    <tr>
                        <th width="30%" scope="col">이름</th>
                        <th width="70%" scope="col">{{student.kor_name}}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">상태</th>
                        <td>{{student.status}}</td>
                    </tr>
                    <tr>
                        <th scope="row">유형</th>
                        <td>{{student.type_choices}}</td>
                    </tr>
                    <tr>
                        <th scope="row">유형상세</th>
                        <td>{{student.type_detail_choices}}</td>
                    </tr>
                    {% if student.status == '재원' %}
                    <tr>
                        <th scope="row">현재반</th>
                        <td>{{student.cur_class}}</td>
                    </tr>
                    {%endif%}
                    <tr>
                        <th scope="row">이전반</th>
                        <td>{{student.last_class}}</td>
                    </tr>
                    <tr>
                        <th scope="row">이동희망반</th>
                        <td>{{student.want_class}}</td>
                    </tr>
                    <tr>
                        <th scope="row">영어이름</th>
                        <td>{{student.eng_name}}</td>
                    </tr>
                    <tr>
                        <th scope="row">학교명</th>
                        <td>{{student.school}}</td>
                    </tr>
                    <tr>
                        <th scope="row">학년</th>
                        <td>{{student.grade}}</td>
                    </tr>
                    <tr>
                        <th scope="row">성별</th>
                        <td>{{student.sex}}</td>
                    </tr>
                    {% if student.cell_phone %}
                    <tr>
                        <th scope="row">학생전화</th>
                        <td>{{student.cell_phone}}</td>
                    </tr>
                    {% endif %}
                    {% if student.cell_d %}
                    <tr>
                        <th scope="row" rowspan="2" style="vertical-align:middle">학부모전화</th>
                        <td>어머님 - {{student.cell_m}}</td>
                    </tr>
                    <tr>
                        <td>아버님 - {{student.cell_d}}</td>
                    </tr>
                    {% else %}
                    <tr>
                        <th scope="row">학부모전화</th>
                        <td>어머님 - {{student.cell_m}}</td>
                    </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">SMS 수신 여부</th>
                        {% if student.get_sms %}
                        <td>수신 허용</td>
                        {% else %}
                        <td>수신 거부</td>
                        {% endif %}
                    </tr>
                    {% if student.quit_date is not None %}
                    <tr>
                        <th scope="row">입학일</th>
                        <td>{{student.registration_date}}</td>
                    </tr>
                    <tr>
                        <th scope="row">휴/퇴원일</th>
                        <td>{{student.quit_date}}</td>
                    </tr>
                    {% elif student.registration_date %}
                    <tr>
                        <th scope="row">입학일</th>
                        <td>{{student.registration_date}}</td>
                    </tr>
                    {%endif %}
                    <tr>
                        <th scope="row">시</th>
                        <td>{{student.si}}</td>
                    </tr>
                    <tr>
                        <th scope="row">구</th>
                        <td>{{student.gu}}</td>
                    </tr>
                    <tr>
                        <th scope="row">동</th>
                        <td>{{student.dong}}</td>
                    </tr>
                    <tr>
                        <th scope="row">상세주소</th>
                        <td>{{student.detail_address}}</td>
                    </tr>

                    {% if consult_list %}
                    <tr>
                        <th scope="row" rowspan="{{consult_list|length|add:"1"}}" style="vertical-align:middle">상담
                        </th>
                    </tr>
                    {% for consult in consult_list%}
                    <tr>
                        <td><a href="{% url 'students:consult-detail' consult.pk %}">{{consult.when_consult}},
                                {{consult.title}}</a> by {{consult.counselor}}</td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    {%endif %}
                </tbody>
            </table>
            <div class='row'>
                <div class='col-sm'>
                </div>
                <div class='col-sm'>
                    <button type="button" class="btn btn-success"
                        onclick="location.href='{% url "students:student-edit" pk=student.pk %}'">수정</button>
                </div>
                <div class='col-sm'>
                </div>
                <div class='col-sm'>
                    <button type="button" class="btn btn-danger"
                        onclick="location.href='{% url "students:student-delete" pk=student.pk %}'">삭제</button>
                </div>
                <div class='col-sm'>
                </div>
            </div>
        </div>
    </div>

        <div class='col-sm'>
        </div>
</div> {% endblock %}